/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.modern_ehealth.util.healmac;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
